#Base image of python
FROM python:latest

#Set the default directory
WORKDIR dashboard

#Copy over requirements
COPY requirements.txt .

#Install all requirements on the container
RUN pip install -r requirements.txt

#Copy over dashboard files
COPY dashboard.py .

COPY power_outages.py .

COPY energy_prices.py .

COPY power_generation.py .

COPY carbon_insights.py .

COPY sign_up.py .

COPY data.py .

COPY power_generation_charts.py .

COPY power_outages_charts.py .

COPY energy_prices_charts.py . 

COPY carbon_insights_charts.py .

#Run the dashboard
CMD streamlit run dashboard.py