# Set the AWS base image for a lambda function 
FROM public.ecr.aws/lambda/python:latest

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install -r requirements.txt

# Load all necessary files for the ETL pipelines
COPY newsletter_queries.py .
COPY summary_report_html.py .
COPY plugged_in_logo.png .

CMD [ "summary_report_html.handler" ]