name: Pytest and pylint

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  linting:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository (clone repo into virtual machine)
        uses: actions/checkout@v3
        
      - name: Install python to the virtual machine
        uses: actions/setup-python@v4.6.0
        
      - name: Install testing modules
        run: pip install pytest pylint 

      - name: Install dashboard dependencies 
        run: |
          cd dashboard
          pip install -r requirements.txt     

      - name: Install carbon reading requirements
        run: |
          cd etl_pipeline/carbon_readings
          pip install -r requirement.txt 
      
      - name: Install carbon reading requirements
        run: |
          cd etl_pipeline/carbon_readings
          pip install -r requirement.txt  

      - name: Install outages requirements
        run: |
          cd etl_pipeline/outages
          pip install -r requirement.txt  

      - name: Install power_readings requirements
        run: |
          cd etl_pipeline/power_readings
          pip install -r requirement.txt  

      - name: Run pylint
        run: pylint --fail-under=8 $(git ls-files '*.py')
  
  run_tests:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository (clone repo into virtual machine)
        uses: actions/checkout@v3
        
      - name: Install python to the virtual machine
        uses: actions/setup-python@v4.6.0
        
      - name: Install testing modules
        run: pip install pytest pylint 

      - name: Install dashboard dependencies 
        run: |
          cd dashboard
          pip install -r requirements.txt     

      - name: Install carbon reading requirements
        run: |
          cd etl_pipeline/carbon_readings
          pip install -r requirement.txt 
      
      - name: Install carbon reading requirements
        run: |
          cd etl_pipeline/carbon_readings
          pip install -r requirement.txt  

      - name: Install outages requirements
        run: |
          cd etl_pipeline/outages
          pip install -r requirement.txt  

      - name: Install power_readings requirements
        run: |
          cd etl_pipeline/power_readings
          pip install -r requirement.txt  
        
      - name: Run tests
        run: pytest