name: Pytest and pylint

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  linting:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository (clone repo into virtual machine)
        uses: actions/checkout@v3
        
      - name: Install python to the virtual machine
        uses: actions/setup-python@v4.6.0
        
      - name: Install our requirements
        run: pip install -r requirements.txt
        
      - name: Run pylint
        run: pylint --fail-under=8 $(git ls-files '*.py')